feat: create domain entities
SoftDevSix/ArgosInstrumentation pull request #1
Opened 2024-11-18 22:36 UTC by zrock-dev

#### Resolved task/US: ([CS-001 Information Receivers](https://app.clickup.com/t/868at94kb))
* * * *

## What's in this pull request?

An implementation of domain entities to develop the instrumenter

## How Has This Been Tested?

Implemented JUNIT tests to verify the implementation works.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-11-19 03:14 UTC, SebasthianSalpozz requested changes
From what I see you have a different configuration than the repository setup task, please put that in order since maybe you got involved in a task that does not belong to you

2024-11-19 05:17 UTC, zrock-dev commented
Dear @SebasthianSalpozz I have updated the base of the PR to point to the repository set-up PR.

2024-11-21 11:40 UTC, SebasthianSalpozz requested changes

2024-11-21 11:40 UTC, SebasthianSalpozz commented on lib/build.gradle.kts.orig
> +<<<<<<< HEAD:build.gradle.kts
Error of bad rebase please solve that

2024-11-21 20:27 UTC, zrock-dev commented on lib/build.gradle.kts.orig
> +<<<<<<< HEAD:build.gradle.kts
I have deleted that file.

2024-11-21 23:31 UTC, SebasthianSalpozz requested changes

2024-11-21 23:31 UTC, SebasthianSalpozz commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +    public ClassData(String className) {
Is there any reason not to use lombok for the constructor?

2024-11-21 23:31 UTC, SebasthianSalpozz commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/CoverageData.java
> +    public CoverageData(ClassData classData, ClassData probeData) {
Is there any reason not to use lombok for the constructor?

2024-11-21 23:31 UTC, SebasthianSalpozz commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java
> +    public MethodData(String name, String desc) {
Is there any reason not to use lombok for the constructor?

2024-11-21 23:31 UTC, SebasthianSalpozz commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java
> +    }
Why you don't see necessary a to String here?

2024-11-22 01:29 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java
> +    }
String.format() ?

2024-11-22 01:52 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/CoverageData.java
> +    public CoverageData(ClassData classData, ClassData probeData) {
That's a great idea. I have added the Lombok annotation.

2024-11-22 01:52 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java
> +    public MethodData(String name, String desc) {
That's a great idea. I have added the Lombok annotation.

2024-11-22 06:24 UTC, sebastian-barra-jalafund commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +    public void saveMethodData(MethodData method, int line) {
the saveMethodData method does not validate if method is null this could cause a NullPointerException.

2024-11-22 11:13 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +    public ClassData(String className) {
That's a great idea. I have added the Lombok annotation.

2024-11-22 11:39 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +    public void saveMethodData(MethodData method, int line) {
I have added the Lombok `@NonNull` annotation to that parameter. Using a validation would be troublesome because the method would throw a null pointer exception again.

2024-11-22 12:24 UTC, SebasthianSalpozz reviewed
just to leave evidence I tell you that when I do "" I get build failed

2024-11-22 12:24 UTC, SebasthianSalpozz commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java
> +    }
I refer to this part of code that we have in the agent :3
![image](https://github.com/user-attachments/assets/d319c572-532e-49f0-8af7-f114d114bcdd)

2024-11-22 13:06 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java
> +    }
I see. Yes, indeed, I have omitted that part of code. That is because, in the agent the end result is to print the coverage report to STDOUT, but in our case we have to produce an object. That's why I think we won't need this particular piece of code, other than for debugging purposes.

2024-11-22 13:08 UTC, zamoranoalicia requested changes

2024-11-22 13:08 UTC, zamoranoalicia commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +    private static final Logger logger = LoggerFactory.getLogger(ClassData.class);
In the future please use @Self4j  https://www.slf4j.org/ for the logs, we can keep this part as it is for now

2024-11-22 13:08 UTC, zamoranoalicia commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +                                    "Attempt to store empty.%n Method name: %s, Method desc: %s",
this messages should be constants

2024-11-22 13:08 UTC, zamoranoalicia commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +                        "Stored method%nClass: %s%nMethod: %s %s%nAt line: %d",
same here this should be constanst

2024-11-22 14:22 UTC, SebasthianSalpozz requested changes
I see that you add a package lib maybe its better to manage all form src

2024-11-22 19:12 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +                                    "Attempt to store empty.%n Method name: %s, Method desc: %s",
Does this mean every log message should be a constant?

2024-11-22 19:15 UTC, zrock-dev commented
Dear @SebasthianSalpozz following today's meeting, I have moved the src folder from lib to the root.

2024-11-25 11:24 UTC, SebasthianSalpozz approved these changes

2024-11-25 11:47 UTC, sebastian-barra-jalafund approved these changes

2024-11-25 11:48 UTC, zamoranoalicia approved these changes
LGTM

2024-11-25 11:52 UTC, zrock-dev commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +                                    "Attempt to store empty.%n Method name: %s, Method desc: %s",
Alright I will implement this changes in a new PR

2024-11-25 12:17 UTC, merged