feat: coverage-collector-implementation
SoftDevSix/ArgosInstrumentation pull request #11
Opened 2024-11-26 12:02 UTC by alex-paca-jalafund

#### Resolved task/US: ([CS-005-1](https://app.clickup.com/t/868azy24a))
* * * *

## What's in this pull request?

In this PR its the implementation of coverage collector, editing the injecter for comunicate with the path ov the coverageCOllector collect method also updating the corresponding test.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Its implemented unit testing for this PR, simulating a valid and not valid collection. Also this PR will be tested for a end to end testing at the end of the complete testing
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-11-26 19:50 UTC, zamoranoalicia requested changes

2024-11-26 19:50 UTC, zamoranoalicia commented on src/main/java/edu/usb/argosinstrumentation/coverageadapter/CodeInjecter.java
> +                "edu/usb/argosinstrumentation/transformer/CoverageCollector",
please use a constant here, you can add a new field on the application properties file and read it using @Value from spring boot

2024-11-26 19:50 UTC, zamoranoalicia commented on src/test/java/edu/usb/argosinstrumentation/coverageadapter/CodeInjecterTest.java
> +                                            "edu/usb/argosinstrumentation/transformer/CoverageCollector",
same here

2024-11-26 22:32 UTC, SebasthianSalpozz requested changes

2024-11-26 22:32 UTC, SebasthianSalpozz commented on src/main/java/edu/usb/argosinstrumentation/transformer/CoverageCollector.java
> +    public CoverageCollector(Map<String, CoverageData> finalInfo) {
This constructor should be declared with lombok I think.

2024-11-27 01:22 UTC, zrock-dev requested changes
Good job. I've requested some changes. 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/SoftDevSix/ArgosInstrumentation/11#-:-OCfBqnK7LwNtipQaec7:bl9ye2l)* status: all files reviewed, 6 unresolved discussions (waiting on @alex-paca-jalafund and @bianca-soliz-jalafund)

___
*[`src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java` line 7 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosInstrumentation/11#-OCf9SFT0Vp3_dqM-PIY:-OCf9SFT0Vp3_dqM-PIZ:b-apx0kx) ([raw file](https://github.com/SoftDevSix/ArgosInstrumentation/blob/087ed25d5a39dfb2e9228b9ce69cc4748730268d/src/main/java/edu/usb/argosinstrumentation/domain/MethodData.java#L7)):*
> ```Java
> import lombok.Getter;
> 
> @AllArgsConstructor
> ```

Please clarify why this annotation is required.
___
*[`src/main/java/edu/usb/argosinstrumentation/transformer/CoverageCollector.java` line 18 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosInstrumentation/11#-OCfB9dV1lGrY69ejzlb:-OCfB9dV1lGrY69ejzlc:b-uw61nn) ([raw file](https://github.com/SoftDevSix/ArgosInstrumentation/blob/087ed25d5a39dfb2e9228b9ce69cc4748730268d/src/main/java/edu/usb/argosinstrumentation/transformer/CoverageCollector.java#L18)):*
> ```Java
>     public static void collect(String className, String methodName, String mDesc, int line) {
>         if (finalInfo.get(className) != null) {
>             MethodData methodData = new MethodData(methodName, mDesc);
> ```

Please use MethodData's builder instead, this way if the class implementation changes this code won't be affected.
___
*[`src/main/java/edu/usb/argosinstrumentation/transformer/CoverageCollector.java` line 21 at r1](https://reviewable.io/reviews/SoftDevSix/ArgosInstrumentation/11#-OCfA1VKA4lVWt5xkq9N:-OCfA1VKA4lVWt5xkq9O:bymwdu1) ([raw file](https://github.com/SoftDevSix/ArgosInstrumentation/blob/087ed25d5a39dfb2e9228b9ce69cc4748730268d/src/main/java/edu/usb/argosinstrumentation/transformer/CoverageCollector.java#L21)):*
> ```Java
>             finalInfo.get(className).getClassData().saveMethodData(methodData, line);
>         } else {
>             System.out.println("final info get className is null at collectMethod");
> ```

Please use a logger instead. This way we will avoid losing important log data.


<!-- Sent from Reviewable.io -->

2024-11-27 02:13 UTC, alex-paca-jalafund commented on src/main/java/edu/usb/argosinstrumentation/transformer/CoverageCollector.java
> +    public CoverageCollector(Map<String, CoverageData> finalInfo) {
Lombok dosn't detect static implementations such us finalInfo, so when i used allArgsConstructor or Builder generates an empty builder, in order to have separate classes i create a manual construct in orther to set the finalInfo during the process.

2024-11-27 02:15 UTC, alex-paca-jalafund commented on src/main/java/edu/usb/argosinstrumentation/coverageadapter/CodeInjecter.java
> +                "edu/usb/argosinstrumentation/transformer/CoverageCollector",
Miss i run into a problem that if i use @Value directly in codeInjecter for some reason its always null but I implemented in the constructor and the class were is going to be used CoverageAdapter Its passing the @Value, when i  do the same implementation in CodeInjecter class SpringBoot trhows an error that says that there is an cyclic call

2024-11-27 12:18 UTC, zamoranoalicia approved these changes
LGTM

2024-11-27 14:24 UTC, closed without merging