fix: injector-path
SoftDevSix/ArgosInstrumentation pull request #21
Opened 2024-12-01 22:03 UTC by alex-paca-jalafund

#### Resolved task/US: ([cs-004](https://app.clickup.com/t/868at9fzm))
* * * *

## What's in this pull request?
Its a fix for the path of the CoverageCollector

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

pass all unit testing
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-12-01 22:17 UTC, zrock-dev commented
Since this PR is labeled as a bug, could you add the reproduction steps please.


<!-- Sent from Reviewable.io -->

2024-12-01 22:22 UTC, alex-paca-jalafund commented
> Since this PR is labeled as a bug, could you add the reproduction steps please.

Its when were are using the jar in other project after configuration, when you want to make the coverage it drops:
![Screenshot from 2024-12-01 18-21-12](https://github.com/user-attachments/assets/0b9f3a89-5ad8-43d7-80d5-98fbd50c710d)

2024-12-02 13:29 UTC, SebasthianSalpozz requested changes

2024-12-02 13:29 UTC, SebasthianSalpozz commented on src/main/java/edu/usb/argosinstrumentation/coverageadapter/CodeInjecter.java
> +                "edu/usb/argosinstrumentation/transformer/CoverageCollector",
I understand the problem but I see that this part would be hardcoding the Collector. Is there no other way to avoid doing this?

2024-12-02 13:31 UTC, alex-paca-jalafund commented on src/main/java/edu/usb/argosinstrumentation/coverageadapter/CodeInjecter.java
> +                "edu/usb/argosinstrumentation/transformer/CoverageCollector",
At the moment no, for this part the class its always setted in null, so when its trying using static collect it breaks:
![Screenshot from 2024-12-02 08-04-08](https://github.com/user-attachments/assets/f2974bee-5752-4c35-830b-cb519d643963)

2024-12-02 13:32 UTC, SebasthianSalpozz commented on src/main/java/edu/usb/argosinstrumentation/coverageadapter/CodeInjecter.java
> +                "edu/usb/argosinstrumentation/transformer/CoverageCollector",
Okay, I understand that for reasons of time we cannot find another way, so if you find another solution for the moment, implement it and assign me as a reviewer.

2024-12-02 13:32 UTC, SebasthianSalpozz approved these changes

2024-12-02 16:03 UTC, zrock-dev commented
I have attempted to reproduce the bug, but instead found a different error message.

### Reproduction steps
1. build a JAR from the most recent version of develop `$ /radlew shadowJar`
2. clone the hello-world sample project `$ git clone --depth=1 --branch=java-test-coverage-tool-asm  https://github.com/SoftDevSix/system-design.git`
3. Replace the coverage.jar file with the produce JAR of step 1
4. Execute tests `./gradldew --no-build-cache clean test`

### Expected result
The execution of the fourth step should show the bug reported by @alex-paca-jalafund. 

### Actual result
A different error
```
AppTest > initializationError FAILED
    java.lang.ClassFormatError at ClassLoader.java:-2
```

![image](https://github.com/user-attachments/assets/5ea162b1-d540-4cb4-a2de-7e4dfd1b55f1)


### Notes
- If I run the same test, this time without using the agent, it executes normally

2024-12-02 16:14 UTC, alex-paca-jalafund commented
> I have attempted to reproduce the bug, but instead found a different error message.
> 
> ### Reproduction steps
> 1. build a JAR from the most recent version of develop `$ /radlew shadowJar`
> 2. clone the hello-world sample project `$ git clone --depth=1 --branch=java-test-coverage-tool-asm  https://github.com/SoftDevSix/system-design.git`
> 3. Replace the coverage.jar file with the produce JAR of step 1
> 4. Execute tests `./gradldew --no-build-cache clean test`
> 
> ### Expected result
> The execution of the fourth step should show the bug reported by @alex-paca-jalafund.
> 
> ### Actual result
> A different error
> 
> ```
> AppTest > initializationError FAILED
>     java.lang.ClassFormatError at ClassLoader.java:-2
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/64939916/391616050-5ea162b1-d540-4cb4-a2de-7e4dfd1b55f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTYzMDUsIm5iZiI6MTczMzE1NjAwNSwicGF0aCI6Ii82NDkzOTkxNi8zOTE2MTYwNTAtNWVhMTYyYjEtZDU0MC00Y2I0LWEyZGUtN2U0ZGZkMWI1NWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZWU1MDU3M2Q0YTIwYTg5ZmNhYTZiZWQ1MWU1MDU2OWQ0MTVhZDg5ZGRiZGJkMjFlM2U0MTFmYjBhYThmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7PKxvPYM7Lqq5ERCWs1CkfMt4iuerlC48sK7Rfxl7u0)
> 
> ### Notes
> * If I run the same test, this time without using the agent, it executes normally
> 
> I have also attempted to reproduce the same steps but this time using a JAR build from this PR `fix/cs-004/injector-path` and I was able to execute the tests successfully which means that this PR is solving the bug.
> 
> @alex-paca-jalafund Is the bug I have just reported the same you have reported?

yes, it's the same.

2024-12-02 16:16 UTC, alex-paca-jalafund commented
> > I have attempted to reproduce the bug, but instead found a different error message.
> > ### Reproduction steps
> > 
> > 1. build a JAR from the most recent version of develop `$ /radlew shadowJar`
> > 2. clone the hello-world sample project `$ git clone --depth=1 --branch=java-test-coverage-tool-asm  https://github.com/SoftDevSix/system-design.git`
> > 3. Replace the coverage.jar file with the produce JAR of step 1
> > 4. Execute tests `./gradldew --no-build-cache clean test`
> > 
> > ### Expected result
> > The execution of the fourth step should show the bug reported by @alex-paca-jalafund.
> > ### Actual result
> > A different error
> > ```
> > AppTest > initializationError FAILED
> >     java.lang.ClassFormatError at ClassLoader.java:-2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/64939916/391616050-5ea162b1-d540-4cb4-a2de-7e4dfd1b55f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNTYzMDUsIm5iZiI6MTczMzE1NjAwNSwicGF0aCI6Ii82NDkzOTkxNi8zOTE2MTYwNTAtNWVhMTYyYjEtZDU0MC00Y2I0LWEyZGUtN2U0ZGZkMWI1NWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDE2MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZWU1MDU3M2Q0YTIwYTg5ZmNhYTZiZWQ1MWU1MDU2OWQ0MTVhZDg5ZGRiZGJkMjFlM2U0MTFmYjBhYThmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7PKxvPYM7Lqq5ERCWs1CkfMt4iuerlC48sK7Rfxl7u0)
> > ### Notes
> > 
> > * If I run the same test, this time without using the agent, it executes normally
> > 
> > I have also attempted to reproduce the same steps but this time using a JAR build from this PR `fix/cs-004/injector-path` and I was able to execute the tests successfully which means that this PR is solving the bug.
> > @alex-paca-jalafund Is the bug I have just reported the same you have reported?
> 
> yes, it's the same, class loader cant find a empty path such us "" that its the problem im solving in this PR.

2024-12-02 16:16 UTC, zrock-dev approved these changes
Okay. So I 've verified the bug has been solved. 

Next time it would be awesome for the bug to have a better documentation to avoid extra work.

2024-12-02 16:20 UTC, merged