feat: add coverage adapter overwriting the visit method
SoftDevSix/ArgosInstrumentation pull request #4
Opened 2024-11-20 14:28 UTC by SebasthianSalpozz

2024-11-20 14:38 UTC, alex-paca-jalafund requested changes

2024-11-20 14:38 UTC, alex-paca-jalafund commented on src/main/java/edu/usb/argosinstrumentation/CoverageAdapter/CoverageAdapter.java
> +    String className;
please add private its an atribute.

2024-11-21 01:12 UTC, SebasthianSalpozz commented on src/main/java/edu/usb/argosinstrumentation/CoverageAdapter/CoverageAdapter.java
> +    String className;
Sure Also I will use a getter to obtain this atribute :D

2024-11-21 09:56 UTC, alex-paca-jalafund approved these changes
Nice work.

2024-11-21 10:55 UTC, alex-paca-jalafund reviewed
Pls add description to the pull request. something like what did you did, why...

2024-11-21 11:29 UTC, merged