Feat/cs 002/information collector
SoftDevSix/ArgosInstrumentation pull request #6
Opened 2024-11-21 00:45 UTC by JosuePrado

This pull implements the information collector class which is in charge of collecting the lines of code of a class.

2024-11-22 02:27 UTC, sebastian-barra-jalafund approved these changes
no observations found, approved

2024-11-25 11:36 UTC, zamoranoalicia requested changes

2024-11-25 11:36 UTC, zamoranoalicia commented on lib/build.gradle.kts.orig
> +    // implementation(libs.springboot.devtools)
remove this commented code

2024-11-25 11:36 UTC, zamoranoalicia commented on lib/build.gradle.kts.orig
> +>>>>>>> 2da96a7 (chore: create gradle lib project):lib/build.gradle.kts
this is an error during the rebase please fix this

2024-11-25 11:36 UTC, zamoranoalicia commented on lib/build.gradle.kts.orig
> +<<<<<<< HEAD:build.gradle.kts
this is an error during the rebase please fix this

2024-11-25 11:36 UTC, zamoranoalicia commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +                                    "Attempt to store empty.%n Method name: %s, Method desc: %s",
please use constants for the messages

2024-11-25 11:36 UTC, zamoranoalicia commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +            throw new InvalidParametersException("Cannot accept empty names");
Please define specific runtime exception here

2024-11-25 22:23 UTC, JosuePrado commented on lib/build.gradle.kts.orig
> +    // implementation(libs.springboot.devtools)
you are right it was a rebase problem, the file was deleted.

2024-11-25 22:23 UTC, JosuePrado commented on lib/build.gradle.kts.orig
> +>>>>>>> 2da96a7 (chore: create gradle lib project):lib/build.gradle.kts
you are right it was a rebase problem, the file was deleted.

2024-11-25 22:23 UTC, JosuePrado commented on lib/build.gradle.kts.orig
> +<<<<<<< HEAD:build.gradle.kts
you are right it was a rebase problem, the file was deleted.

2024-11-25 22:24 UTC, JosuePrado commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +                                    "Attempt to store empty.%n Method name: %s, Method desc: %s",
another problem with the source branch that class does not belong to this pull request

2024-11-25 22:24 UTC, JosuePrado commented on lib/src/main/java/edu/usb/argosinstrumentation/domain/ClassData.java
> +            throw new InvalidParametersException("Cannot accept empty names");
another problem with the source branch that class does not belong to this pull request

2024-11-26 19:45 UTC, zamoranoalicia approved these changes
LGTM

2024-11-26 19:45 UTC, zamoranoalicia commented on src/test/java/edu/usb/argosinstrumentation/collector/CounterTest.java
> +import org.objectweb.asm.*;
please dont use this kind of imports

2024-11-26 19:45 UTC, zamoranoalicia commented on src/test/java/edu/usb/argosinstrumentation/collector/CounterTest.java
> +import org.objectweb.asm.*;
we are going to merge this because it is blocking another ticket but in the future dont do this

2024-11-26 19:46 UTC, merged